spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
    hikari:
      maximum-pool-size: 10
  h2:
    console:
      enabled: true

mybatis:
  configuration:
    lazy-loading-enabled: true
  mapper-locations:
    - 'classpath:/mapper/*.xml'
  type-aliases-package: com.kenny.minbatistest.domain;
    com.kenny.minbatistest.infra;

logging:
  level:
    com.kenny.minbatistest: DEBUG
